[project]
name = "dev.py"
version = "0.1a2.dev0"
requires-python = ">=3.7"
description = "Developer tool for scientific Python libraries"
license = {file = "LICENSE"}
maintainers = [
  {name = "Scientific Python", email = "dev.py@discuss.scientific-python.org"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dependencies = [
  "click",
  "toml"
]

[project.optional-dependencies]
lint = ["pre-commit >= 2.20"]

[project.urls]
homepage = "https://github.com/scientific-python/dev.py"

[tool.setuptools.packages.find]
include = ["dev"]

[tool.dev.py]
package = 'dev'
commands = ["dev.py.build", "dev.py.test", "dev.py.shell", "dev.py.ipython", "dev.py.python", "custom/__init__.py:example"]
